/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.99
 * Generated at: 2024-04-23 11:27:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.kh.thenolja.member.model.vo.Member;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(1);
    _jspx_imports_classes.add("com.kh.thenolja.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>로그인 페이지</title>\r\n");
      out.write("	<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\">\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("	<style>\r\n");
      out.write("		/*div{border: 1px solid red;}*/\r\n");
      out.write("		#wrap{\r\n");
      out.write("			width: 1200px;\r\n");
      out.write("			height: 600px;\r\n");
      out.write("			margin: auto;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		#content{\r\n");
      out.write("			width: 50%;\r\n");
      out.write("			margin: auto;\r\n");
      out.write("			border: 1px solid lightgray;\r\n");
      out.write("			margin-top: 50px;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.content{\r\n");
      out.write("			width: 100%;\r\n");
      out.write("			margin: auto;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		#content2{\r\n");
      out.write("			color: lightgray;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		#loginword{margin-top: 10px; color: rgb(70, 149, 151);}\r\n");
      out.write("\r\n");
      out.write("		#loginword > span{\r\n");
      out.write("			text-align: center; \r\n");
      out.write("			height: 100px;\r\n");
      out.write("			font-size: 40px;\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		#login-area{width: 100%; height: 100%;}\r\n");
      out.write("		\r\n");
      out.write("		#id, #password{\r\n");
      out.write("			margin-top: 20px;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		#id{\r\n");
      out.write("			background-image: url('resources/login/person.png');\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		#password{\r\n");
      out.write("			background-image: url('resources/login/password.png');\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.input{\r\n");
      out.write("			outline-color: rgb(70, 149, 151);\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.input{\r\n");
      out.write("			width: 400px;\r\n");
      out.write("			height: 50px;\r\n");
      out.write("			border-color: rgb(230, 230, 230);\r\n");
      out.write("			border-radius: 10px;\r\n");
      out.write("			background-repeat: no-repeat;\r\n");
      out.write("			background-size: 30px;\r\n");
      out.write("			background-position: right;\r\n");
      out.write("		}\r\n");
      out.write("		#content{text-align: center;}\r\n");
      out.write("\r\n");
      out.write("		#content2 > a{\r\n");
      out.write("			text-decoration: none;\r\n");
      out.write("			color: rgb(99, 99, 99);\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		#content3{\r\n");
      out.write("			margin-top: 50px;\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		.loginBtn{\r\n");
      out.write("			width: 400px;\r\n");
      out.write("			height: 50px;\r\n");
      out.write("			background-color: rgb(70, 149, 151);\r\n");
      out.write("			color: white;\r\n");
      out.write("			font-size: 20px;\r\n");
      out.write("			font-weight: bold;\r\n");
      out.write("			margin-bottom: 30px;\r\n");
      out.write("			border:none;\r\n");
      out.write("		}\r\n");
      out.write("		.loginBtn:hover{color:lightgray;}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../common/menubar.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("      \r\n");
      out.write("		<div id=\"wrap\">\r\n");
      out.write("			<div id=\"content\">\r\n");
      out.write("				<div id=\"loginword\">\r\n");
      out.write("					<span>로그인</span>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div id=\"login-area\" class=\"content\">\r\n");
      out.write("					<form action=\"login.member\" method=\"post\">\r\n");
      out.write("						<div id=\"content1\">\r\n");
      out.write("							<input type=\"text\" name=\"memId\" id=\"id\" class=\"input\" placeholder=\"아이디\" maxlength=\"12\" autofocus required>\r\n");
      out.write("							<input type=\"password\" name=\"memPwd\" id=\"password\" class=\"input\" placeholder=\"비밀번호\" maxlength=\"15\" required>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div id=\"content2\" class=\"content\">\r\n");
      out.write("							<br><br>\r\n");
      out.write("							<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/findIdPage\">아이디 찾기</a>\r\n");
      out.write("							&nbsp;&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("							<a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ path }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/findPwdPage\">비밀번호 찾기</a>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("						<div id=\"content3\">\r\n");
      out.write("							<button type=\"submit\" class=\"loginBtn\">로그인</button>\r\n");
      out.write("						</div>\r\n");
      out.write("\r\n");
      out.write("					</form>\r\n");
      out.write("				\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		\r\n");
      out.write("		</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
